matrix:
  include:
  - language: python
    python: "3.5"
    install: "pip install pyyaml"
    script: make test
  - language: android
    jdk: oraclejdk8
    android:
      components:
        - tools
        - android-26
        - build-tools-26.0.2
    before_script: cd AndroidServer
    script: ./gradlew build connectedCheck
