jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.5"
      # command to run tests
      install:
        - "pip install pyyaml"
      script:
        - make test

      before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
    - stage: android_server
      language: android
      android:
        components:
          - build-tools-18.1.1
          - android-18
          - extra
      script:
        - cd AndroidServer ; ./gradlew build
